drop table if exists orders;

CREATE TABLE ORDERS  ( O_ORDERKEY       INTEGER NOT NULL PRIMARY KEY,
	O_CUSTKEY        INTEGER NOT NULL,
	O_ORDERSTATUS    CHAR(1) NOT NULL,
	O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
	O_ORDERDATE      DATE NOT NULL,
	O_ORDERPRIORITY  CHAR(15) NOT NULL,  
	O_CLERK          CHAR(15) NOT NULL, 
	O_SHIPPRIORITY   INTEGER NOT NULL,
	O_COMMENT        VARCHAR(79) NOT NULL);

COPY orders from '../data_sf10/orders.tbl' (DELIMITER '|');
